### ISSUE TITLE
Wav audio files can not be edited tags.

### ISSUE THREAD

**Issue by Explorer00** [reyanshmishra/Rey-MusicPlayer#12]
#### expected behavior
Supposedly all audio files like (WAV, AAC, etc.) can edit tags.

#### Real behavior
While I edit the tags in a wav audio file the application suddenly breaks down.

#### How to reproduce
- Download app in play store.
- Run the app.
- Find the audio file wav.
- then click on point 3 on the right side.
- select the feature "Edit Tags".
- Bugs are visible.
- Browser: Boom v3.4.31
- Operating system: xiomi redmi 4A, Android v6.0.1

#### Recording Of The Bug
https://youtu.be/k8m5LbTbw6c

**Comment by reyanshmishra** [comment]
As I am using [JaudioTagger](http://www.jthink.net/jaudiotagger/). It has limited support for the wav files.
