### ISSUE TITLE
Bug found in Boom app while change from portrait to landscape in go to this album

### ISSUE THREAD

**Issue by darewealth** [reyanshmishra/Rey-MusicPlayer#2]
EXPECTED BEHAVIOR
I should be able to access album whether portrait or landscape.

ACTUAL BEHAVIOR
When i change from portrait to landscape the app crashes

HOW TO REPRODUCE

Download 

Launch the app and open

Play any song and click on the 3 dot click go to

And click on go to this album Rotate your screen to landscape and note the bug

Device used: Gionee P5 mini

Operating system: Android version 5.1

App version: 3.4.41

Recording of the Bug
https://youtu.be/uA_zH9RYNSg

**Comment by reyanshmishra** [comment]
Fixed.
