### ISSUE TITLE
How to pull the equalizer 

### ISSUE THREAD

**Issue by neelayak** [reyanshmishra/Rey-MusicPlayer#23]
Great library I am trying to customize the equalizer but when I pull the code and try to use it for demo purpose the equalizer not work at all any source for the Equalizer

**Comment by reyanshmishra** [comment]
Please, can you give me more context?

**Comment by neelayak** [comment]
Bro I am trying to  customize the eq but when I try to run the eq the Preset were not being extracted, Earlier i use shared preference with gson to store date  but while executing the Eq I am getting null list of preset and while passing the media session ID the eq is not doing any audio effect

**Comment by reyanshmishra** [comment]
I don't think this is bug is related to this app so I am closing it, feel free to open if you find any bug with this app.
