### ISSUE TITLE
Bug found in Boom app while change from portrait to landscape in create playlist

### ISSUE THREAD

**Issue by darewealth** [reyanshmishra/Rey-MusicPlayer#3]
EXPECTED BEHAVIOR
I should be able to create playlist whether portrait or landscape.

ACTUAL BEHAVIOR
When i change from portrait to landscape the app crashes

HOW TO REPRODUCE

Download 

Launch the app and open

Click on the 3 dot at the front of song

Go to Add to playlist then click on New playlist Rotate your screen to landscape and note the bug

Device used: Gionee P5 mini

Operating system: Android version 5.1

App version: 3.4.41

Recording of the Bug
https://youtu.be/1I4DbWnX-2A

**Comment by reyanshmishra** [comment]
Fixed.
