### ISSUE TITLE
Boom : Back button doesn't works

### ISSUE THREAD

**Issue by imvrs95** [reyanshmishra/Rey-MusicPlayer#4]
Expected behavior
Back button was supposed to work.

Actual behavior
Back button doesn't works.

How to reproduce
Download the app from F-DROID

Launch the app

Go to menu on top right

Go to purchase

Press back ⬅️button on top left ( which doesn't works )

Browser/App version: v3.4.41
Operating system:
Android 8.1.0 Model Pixel XL

**Comment by reyanshmishra** [comment]
Probably removed this features. It must have been a mistake.
