### ISSUE TITLE
App crashes when a song on play is added to a new playlist via the 'Go to Artist` Option

### ISSUE THREAD

**Issue by organik1** [reyanshmishra/Rey-MusicPlayer#7]
Boom musicplayer crashes on adding a current playing song to a new playlist.

#### Expected behavior

The app shouldn't crash.

#### Actual behavior

Boom musicplayer crashes when a new playlist is created through a now playing song.

#### How to reproduce

* Launch Boom musicplayer and locate the `song` tab on the library.

* Play a song, and you should arrive at the now playing screen.

* Click on three vertical dots next tothe title ticker and choose `Go to`.

* Choose `go to this artist` and locate song on the artist page.

* Click on the three vertical dots on the song, and choose `add to playlist`. (You may need to scroll down the menu to find it)

* Choose create a playlist and input a title.

* Click `okay` and wait for the success toast.

* Browser/App version: V3.4.41

* Operating system: Android v6.0 marshmallow.
   * Chipset: Spread

   * Storage in use: Only Internal memory (8gb)

* Device: Itel p12

**Comment by reyanshmishra** [comment]
Fixed.
